# Generated by Django 2.2.9 on 2020-02-02 01:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_image', to='image.CustomImage')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name as it appears on the map.', max_length=255)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('node_html', models.TextField(blank=True)),
                ('node_image', models.ForeignKey(blank=True, help_text='Replaces the dot with an image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_image', to='image.CustomImage')),
                ('overlay_image', models.ForeignKey(blank=True, help_text='A transparent layer over the whole map that is related to this location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overlay_image', to='image.CustomImage')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
