# Generated by Django 2.2.9 on 2020-02-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('continent', 'Continent'), ('ocean', 'Ocean'), ('hidden', 'Hidden')], default='standard', max_length=255, null=True),
        ),
    ]
