# Generated by Django 2.2.9 on 2020-02-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200202_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='rotate',
            field=models.CharField(blank=True, help_text='Rotates the icon/title on the map, in degrees (180, -45, 90, etc)', max_length=10),
        ),
    ]
