# Generated by Django 2.2.9 on 2020-02-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20200203_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='height',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maplocation',
            name='width',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maplocation',
            name='x',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maplocation',
            name='y',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
