# Generated by Django 2.2.9 on 2020-02-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20200203_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='node_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
