# Generated by Django 2.2.9 on 2020-02-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_maplocation_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='node_css',
            field=models.TextField(blank=True),
        ),
    ]
