# Generated by Django 2.2.9 on 2020-02-05 04:09

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('map', '0010_maplocation_node_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplocation',
            name='node_image',
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='type',
            field=models.CharField(choices=[('continent', 'Continent'), ('hidden', 'Hidden'), ('ocean', 'Ocean'), ('none', 'Not on map'), ('standard', 'Standard'), ('text', 'Text'), ('turtle', 'Turtle')], default='standard', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MapLocationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, help_text='Replaces the dot with an image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_image', to='image.CustomImage')),
                ('location', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_image', to='map.MapLocation')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
