# Generated by Django 2.2.9 on 2020-02-06 03:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('map', '0011_auto_20200205_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplocation',
            name='overlay_image',
        ),
        migrations.AlterField(
            model_name='maplocationimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_image', to='image.CustomImage'),
        ),
        migrations.CreateModel(
            name='MapLocationOverlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overlay_image', to='image.CustomImage')),
                ('location', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlay_image', to='map.MapLocation')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
