# Generated by Django 2.2.6 on 2019-10-31 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicpage',
            name='comic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='image.CustomImage'),
        ),
    ]
