# Generated by Django 2.2.6 on 2019-11-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0004_auto_20191104_0529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comicpage',
            options={'ordering': ['page_number']},
        ),
        migrations.AddField(
            model_name='comicchapter',
            name='chapter_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
