# Generated by Django 2.2.6 on 2019-11-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('comic', '0005_auto_20191104_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicfolder',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='image.CustomImage'),
        ),
    ]
