# Generated by Django 2.2.9 on 2020-01-26 22:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=255, null=True)),
                ('text', models.TextField(blank=True, help_text='Supports markdown formatting.')),
            ],
            options={
                'ordering': ['command'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='BotCommandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('command', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='bot.BotCommand')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_command_image', to='image.CustomImage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
