# Generated by Django 2.2.6 on 2019-11-19 17:30

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('home', '0002_auto_20191113_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('One_Column', wagtail.core.blocks.StructBlock([('column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-one_column', required=False)), ('row_options', wagtail.core.blocks.StructBlock([], required=False))], icon='one-column')), ('Two_Columns', wagtail.core.blocks.StructBlock([('left_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-two_columns_left', required=False)), ('right_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-two_columns_right', required=False)), ('row_options', wagtail.core.blocks.StructBlock([], required=False))], icon='two-columns')), ('Three_Columns', wagtail.core.blocks.StructBlock([('left_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-three_columns_left', required=False)), ('center_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-three_columns_center', required=False)), ('right_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-three_columns_right', required=False)), ('row_options', wagtail.core.blocks.StructBlock([], required=False))], icon='three-columns'))], blank=True),
        ),
        migrations.CreateModel(
            name='HeroLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('home_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_image_layers', to='home.HomePage')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='image.CustomImage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
