# Generated by Django 2.2.6 on 2019-11-20 02:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191119_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('HTML', wagtail.core.blocks.StructBlock([('html_content', wagtail.core.blocks.TextBlock())], icon='fa-code')), ('One_Column', wagtail.core.blocks.StructBlock([('row_options', wagtail.core.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=False))], required=False)), ('column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-one_column', required=False))], icon='one-column')), ('Two_Columns', wagtail.core.blocks.StructBlock([('row_options', wagtail.core.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=False))], required=False)), ('left_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-two_columns_left', required=False)), ('right_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-two_columns_right', required=False))], icon='two-columns')), ('Three_Columns', wagtail.core.blocks.StructBlock([('row_options', wagtail.core.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=False))], required=False)), ('left_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-three_columns_left', required=False)), ('center_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-three_columns_center', required=False)), ('right_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-three_columns_right', required=False))], icon='three-columns'))], blank=True),
        ),
    ]
