# Generated by Django 2.2.9 on 2020-01-26 22:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191122_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('HTML', wagtail.core.blocks.StructBlock([('html_content', wagtail.core.blocks.TextBlock(classname='code-editor'))], icon='fa-code')), ('One_Column', wagtail.core.blocks.StructBlock([('row_options', wagtail.core.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=False))], required=False)), ('column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-one_column', required=False))], icon='one-column')), ('Two_Columns', wagtail.core.blocks.StructBlock([('row_options', wagtail.core.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=False))], required=False)), ('left_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-two_columns_left', required=False)), ('right_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-two_columns_right', required=False))], icon='two-columns')), ('Three_Columns', wagtail.core.blocks.StructBlock([('row_options', wagtail.core.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=False))], required=False)), ('left_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-three_columns_left', required=False)), ('center_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-three_columns_center', required=False)), ('right_column', wagtail.core.blocks.StructBlock([('column_options', wagtail.core.blocks.StructBlock([('classes', wagtail.core.blocks.CharBlock(help_text='Apply custom classes to this column.', max_length=255, required=False))])), ('content', wagtail.core.blocks.RichTextBlock(classname='column-content', required=False))], classname='field-three_columns_right', required=False))], icon='three-columns')), ('Full_Size_Image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Full width, full height'))], icon='form'))], blank=True),
        ),
    ]
