# Generated by Django 2.2.6 on 2019-10-31 02:29

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('accessory', 'Accessory'), ('arm', 'Arm'), ('barbel', 'Barbel'), ('body', 'Body'), ('crest', 'Crest'), ('cape', 'Cape'), ('collar', 'Collar'), ('ear', 'Ear'), ('fluff', 'Fluff'), ('face', 'Face'), ('foot', 'Foot'), ('fur', 'Fur'), ('fin', 'Fin'), ('gem', 'Gem'), ('head', 'Head'), ('hip-skirt', 'Hip Skirt'), ('horn', 'Horn'), ('hand', 'Hand'), ('hip', 'Hip'), ('leg', 'Leg'), ('other', 'Other'), ('poncho', 'Poncho'), ('shale', 'Shale'), ('tail-shard', 'Tail Shard'), ('tail', 'Tail'), ('tail-plate', 'Tail Plate'), ('tail-prong', 'Tail Prong'), ('whisker', 'Whisker'), ('wing', 'Wing')], max_length=24, null=True)),
                ('subspecies', models.CharField(blank=True, choices=[('none', 'None'), ('arctic', 'Arctic'), ('desert', 'Desert'), ('deepforge', 'Deepforge'), ('deepsea', 'Deepsea'), ('drenched', 'Drenched'), ('fuu', 'Fuu'), ('kelpie', 'Kelpie'), ('mountain', 'Mountain'), ('mudskipper', 'Mudskipper'), ('sheep', 'Sheep'), ('saber', 'Saber'), ('sloth', 'Sloth'), ('severblight', 'Severblight'), ('tropical', 'Tropical'), ('vampire', 'Vampire')], default='none', max_length=24)),
                ('rarity', models.CharField(choices=[('none', 'None'), ('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('legendary', 'Legendary')], default='none', max_length=24, null=True)),
                ('sex', models.CharField(choices=[('x', 'Any'), ('f', 'Female'), ('m', 'Male')], default='x', max_length=24, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.CustomImage')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
