# Generated by Django 2.2.6 on 2019-10-23 03:51

from django.db import migrations, models
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(choices=[('stareater', 'Stareater'), ('starsweeper', 'Starsweeper'), ('stardasher', 'Stardasher'), ('starfisher', 'Starfisher'), ('starweaver', 'starweaver'), ('starrobber', 'Starrobber'), ('starcrafter', 'Starcrafter'), ('starshooter', 'Starshooter'), ('chimera', 'Chimera')], max_length=24)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
