# Generated by Django 2.2.6 on 2019-11-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trait', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traittype',
            name='plural_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
