# Generated by Django 2.2.6 on 2019-10-31 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
        ('trait', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.Species'),
        ),
    ]
