# Generated by Django 2.2.6 on 2019-11-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trait', '0002_traittype_plural_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
