# Generated by Django 2.2.6 on 2019-11-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trait', '0003_auto_20191104_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trait',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='traittype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='trait',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trait',
            name='rarity',
            field=models.CharField(choices=[('none', 'None'), ('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('legendary', 'Legendary')], default='none', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='sex',
            field=models.CharField(choices=[('x', 'Unisex'), ('f', 'Feminine'), ('m', 'Masculine')], default='x', max_length=1, null=True),
        ),
    ]
