# Generated by Django 2.2.6 on 2019-11-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trait', '0005_auto_20191112_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trait',
            options={'ordering': ['name']},
        ),
    ]
