# Generated by Django 2.2.6 on 2019-11-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trait', '0006_auto_20191124_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('legendary', 'Legendary')], default='common', max_length=16, null=True),
        ),
    ]
