# Generated by Django 2.2.6 on 2019-11-26 07:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_species_emblem'),
        ('trait', '0007_auto_20191124_2234'),
        ('image', '0001_initial'),
        ('stardragon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stardragon',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved?'),
        ),
        migrations.AddField(
            model_name='stardragon',
            name='buyer_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stardragon',
            name='design_type',
            field=models.CharField(choices=[('official', 'Official'), ('slot', 'Slot'), ('myo', 'Make Your Own')], default='official', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stardragon',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stardragon',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid?'),
        ),
        migrations.AddField(
            model_name='stardragon',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stardragon',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stardragon',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stardragon',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('legendary', 'Legendary')], default='common', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='stardragon',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stardragon',
            name='sex',
            field=models.CharField(choices=[('x', 'Unisex'), ('f', 'Feminine'), ('m', 'Masculine')], default='x', max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='StardragonTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('stardragon', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='stardragon.Stardragon')),
                ('trait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trait.Trait')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StardragonSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('stardragon', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='stardragon.Stardragon')),
                ('subspecies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.SubSpecies')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StardragonLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, choices=[('sale_posting', 'Sale Posting'), ('furaffinity', 'Furaffinity'), ('deviantart', 'Deviantart'), ('other', 'Other')], max_length=255)),
                ('stardragon', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='stardragon.Stardragon')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StardragonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='image.CustomImage')),
                ('stardragon', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stardragon.Stardragon')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StardragonDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('designer', models.CharField(blank=True, max_length=255)),
                ('stardragon', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='designers', to='stardragon.Stardragon')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StardragonColorPalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('stardragon', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='stardragon.Stardragon')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
