# Generated by Django 2.2.6 on 2019-11-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_species_emblem'),
        ('stardragon', '0002_auto_20191126_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stardragonspecies',
            name='subspecies',
        ),
        migrations.AddField(
            model_name='stardragonspecies',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.Species'),
        ),
    ]
