# Generated by Django 2.2.6 on 2019-12-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stardragon', '0004_stardragon_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='stardragon',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
