# Generated by Django 2.2.6 on 2019-11-03 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
    ]
