# Generated by Django 2.2.6 on 2019-11-04 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_auto_20191103_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subspecies',
            options={'ordering': ['species']},
        ),
    ]
