# Generated by Django 2.2.6 on 2019-11-04 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('species', '0003_auto_20191104_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='subspecies',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.CustomImage'),
        ),
    ]
