# Generated by Django 2.2.6 on 2019-11-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0004_subspecies_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name_plural': 'Species'},
        ),
    ]
