# Generated by Django 2.2.6 on 2019-11-06 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('species', '0005_auto_20191104_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='subspecies',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_background', to='image.CustomImage'),
        ),
        migrations.AlterField(
            model_name='subspecies',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_image', to='image.CustomImage'),
        ),
    ]
