# Generated by Django 2.2.6 on 2019-11-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_auto_20191106_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subspecies',
            options={'ordering': ['sort_order']},
        ),
    ]
