# Generated by Django 2.2.6 on 2019-11-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0008_subspecies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='color',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
