# Generated by Django 2.2.6 on 2019-11-24 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('species', '0009_species_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='emblem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_emblem', to='image.CustomImage'),
        ),
    ]
